FROM node:18 as build
ENV NODE_ENV production
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html

