FROM node:18 as build
ENV NODE_ENV production
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
RUN npm run build

FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
# SSL config files (stored on the server only)
COPY beerboss_ca_chain.crt /etc/ssl/beerboss_ca_chain.crt 
COPY server.key /etc/ssl/server.key
COPY --from=build /app/build /usr/share/nginx/html

